server:
  port: 8201

zimug:
  jwt:
    enabled: true
    secret: fjkfaf;afa
    expiration: 3600000
    header: JWTHeaderName
    userParamName: username
    pwdParamName: password
    useDefaultController: true
    corsAllowedOrigins:
      - ENC(ONnX6mbGgwEKLWbEgsOQCx5DsFsNJ2RKj1n/G0vb3Ds=)
    corsAllowedMethods:
      - GET
      - POST
    devOpeningURI:
    permitAllURI:


spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://123.56.169.21:3306/dongbbdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: dongbb
    password: ENC(0mtwFC+OcduHt3cqooFt/GHZm18UXvXQ)
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml

# debug: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.zimug.dongbb.server.jwt: debug
  pattern:
    console: '%red(%d{yyyy-MM-dd HH:mm:ss}) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger{10}) - %cyan(%msg%n)'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger : %msg%n'